### ISSUE TITLE
Add clippy to homepage

### ISSUE THREAD

**Issue by AdamSabla** [stevegrunwell/son-of-clippy#2]
Hello,

Is there any easy way to display Clippy on the homepage, instead of the editor?
I'm just a designer, so I'm really dumb when it comes to code.

Any help much appreciated. Thanks!

**Comment by stevegrunwell** [comment]
Hey @AdamSabla,

The underlying library is [clippy.js](https://www.smore.com/clippy-js), so it could be added pretty easily anywhere (WordPress or otherwise).

Within WordPress, you'll want to enqueue the script and stylesheet using [`wp_enqueue_script()`](https://developer.wordpress.org/reference/functions/wp_enqueue_script/) and [`wp_enqueue_style()`](https://developer.wordpress.org/reference/functions/wp_enqueue_style/), respectively. [`wp_add_linline_script()`](https://developer.wordpress.org/reference/functions/wp_add_inline_script/) can also be useful, if you don't plan to do much more than initializing Clippy.

You can [take a look at how Clippy is scripted in this plugin](https://github.com/stevegrunwell/son-of-clippy/blob/develop/assets/js/src/son_of_clippy.js#L11) to get a sense of defining Clippy's behavior; after we show whichever "agent" has been selected, we make Clippy "speak" the "{user}, it looks like you're trying to write a {post_type}; want some help?" message. Finally, we listen for the post being autosaved and, when it happens, show the "Save" animation.

Hope that helps!

**Comment by AdamSabla** [comment]
Hi @stevegrunwell , thank you very much! You're very helpful.
